name: vote_backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi>=0.100.0
    - uvicorn>=0.23.0
    - sqlalchemy>=2.0.19
    - pymysql>=1.1.0
    - python-dotenv>=1.0.0
    - pydantic>=2.1.0
    - redis>=4.5.5